apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
          - name: account
            image: 'ninasavoy/account:latest'
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 8080
            env:
              - name: DATABASE_HOST
                valueFrom:
                  configMapKeyRef:
                    name: postgres-configmap
                    key: POSTGRES_HOST

              - name: DATABASE_USER
                valueFrom:
                  secretKeyRef:
                    name: postgres-secrets
                    key: POSTGRES_USER

              - name: DATABASE_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgres-secrets
                    key: POSTGRES_PASSWORD